version: 2

jobs:
    build:
        docker:
            - image: nmarkgraf/python-pandoc:1.0
        steps:
            - checkout
            - run:
                name: Update Python PIP if necassary
                command: |
                    source ~/venv/bin/activate
                    pip install --upgrade pip
            - run:
                name: Activate venv and install requierments
                command: |
                    python3 -m venv ~/venv
                    source ~/venv/bin/activate
                    pip install panflute
            - run:
                name: Run tests
                command: |
                    source ~/venv/bin/activate
                    python3 -m unittest test/typography_unittest.py
